export type ValidSkills =
  | "Next.js"
  | "React"
  | "GraphQL"
  | "Nest.js"
  | "express.js"
  | "Node.js"
  | "MongoDB"
  | "Typescript"
  | "Javascript"
  | "HTML 5"
  | "CSS 3"
  | "Redux"
  | "Material UI"
  | "Tailwind CSS"
  | "AWS"
  | "Bootstrap"
  | "OAuth"
  | "MySQL"
  | "Python"
  | "Docker"
  | "Kubernetes"
  | "PostgreSQL"
  | "Redis"
  | "Git"
  | "CI/CD"
  | "Jenkins"
  | "Sass"
  | "Azure"
  | "Google Cloud"
  | "Figma"
  | "Webpack"
  | "Jest"
  | "Cypress"
  | "Storybook"
  | "Prisma"
  | "Three.js"
  | "Laravel"
  | "PHP"
  | "Drupal"
  | "Wordpress"
  | "Strapi"
  | "SonarQube"
  | "Cypress"
  | "Testing Library"
  | "Scrum"
  | "GSAP"
  | "styled-components"
  | "Flask"
  | "SQL"
  | "NoSQL"
  | "UX"
  | "Research"
  | "Big Data"
  | "Management"
  | "Governance"
  | "ITIL"
  | "C++"
  | "UI"
  | "Accessibility"
  | "User Research"
  | "Information Architecture"
  | "Interaction Design"
  | "Prototyping"
  | "Wireframing"
  | "User Flows"
  | "Adobe XD"
  | "Sketch"
  | "InVision"
  | "Miro"
  | "Usability Testing"
  | "A/B Testing"
  | "Design Thinking"
  | "Framer Motion";

export type ValidCategory =
  | "Full Stack"
  | "Frontend"
  | "Backend"
  | "UX"
  | "UI"
  | "Web Dev"
  | "Mobile Dev"
  | "DesignOps"
  | "DevOps"
  | "Design System"
  | "Atomic Design"
  | "3D Modeling";

export type ValidExpType = "Personal" | "Professional";

export type ValidPages =
  | "home"
  | "skills"
  | "projects"
  | "experience"
  | "contact"
  | "education"
  | "resume";
