export const siteConfig = {
  name: "Fernando Camilotti | Developer Portfolio",
  authorName: "Fernando Camilotti",
  username: "fernandocamilotti",
  description:
    "Fernando Camilotti's portfolio - Senior Software Engineer specializing in React, front-end architecture, and design systems. I build fast, intuitive, and scalable web applications.",
  url: "http://www.fernandocamilotti.com",
  links: {
    linkedin: "https://www.linkedin.com/in/fernandocamilotti/?locale=en_US",
  },
  ogImage:
    "https://res.cloudinary.com/moshpit/image/upload/v1764443208/foto_abuksz.jpg",
  iconIco:
    "https://res.cloudinary.com/moshpit/image/upload/v1764443977/1-dcb07074_a4sffg.ico",
  logoIcon:
    "https://res.cloudinary.com/moshpit/image/upload/v1764443967/Icon_okurwv.png",
  keywords: [
    "Fernando Camilotti",
    "Full Stack Engineer",
    "Full Stack Developer",
    "Design Engineer",
    "DesignOps Engineer",
    "Frontend Engineer",
    "Frontend Developer",
    "React",
    "JavaScript",
    "TypeScript",
    "Node.js",
    "Express.js",
    "HTML",
    "CSS",
    "SASS",
    "styled-components",
    "Next.js",
    "Nest.js",
    "Vue.js",
    "Redux",
    "GraphQL",
    "REST APIs",
    "Microfrontends",
    "Design Systems",
    "Storybook",
    "UI Architecture",
    "UX Design",
    "Figma",
    "DesignOps",
    "Frontend Architecture",
    "Web Performance",
    "High-performance UI",
    "Responsive Design",
    "Web Accessibility",
    "Cypress",
    "Jest",
    "Testing Library",
    "Unit Testing",
    "DevOps",
    "CI/CD",
    "Docker",
    "AWS",
    "Azure",
    "Jenkins",
    "Git",
    "GitHub",
    "Scrum",
    "Agile",
    "MongoDB",
    "SQL",
    "PostgreSQL",
    "Kafka",
    "RabbitMQ",
    "Drupal",
    "WordPress",
    "Strapi",
    "Data Visualization",
    "Big Data",
    "Microservices",
    "Form Builders",
    "Component Libraries",
    "User-Centered Design",
    "System Architecture",
    "Software Engineering",
    "Frontend Engineering",
    "Full Stack Development",
    "Interaction Design",
    "Animation (GSAP)",
    "CMS Development",
    "SSR",
    "Cloudflare Caching",
    "Bare-metal Server Management",
    "Code Review",
    "Mentoring",
    "Team Leadership",
    "Cross-functional Collaboration",
    "Technical Documentation",
    "API Design",
    "Product Development",
    "Design-to-Dev Handoff",
  ],
};
